### ISSUE TITLE
Exec option

### ISSUE THREAD

**Issue by UnaiFernandez** [IkerGalardi/LMake#12]
After compiling the code using a command to execute the binaries automatically instead of writing a command to execute them by hand would be awesome. Sometimes this could be ponderous, especially if you have multiple paramters, and the command ends up being too long.

**Comment by IkerGalardi** [comment]
This would be implemented as an lmake command.
`lmake_exec(prog_argv)` where:

- prog_argv: Bash like syntax, command and arguments separated by spaces.

**Comment by IkerGalardi** [comment]
Being worked on. Branch command-exec.

**Comment by IkerGalardi** [comment]
Implemented on commit [f1c8993181d76c74fe922475640b2bc850e8d85d](https://github.com/IkerGalardi/LMake/commit/f1c8993181d76c74fe922475640b2bc850e8d85d) on master.
